import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes, randomInt, randomUUID, createHash } from 'node:crypto';

test('GitHub sign-in validates OAuth and creates isolated opaque sessions', { skip: !process.env.POMOGIT_TEST_DATABASE_URL }, async (t) => {
  const url = new URL(process.env.POMOGIT_TEST_DATABASE_URL);
  assert.match(url.pathname, /_(test|verification)$/);
  Object.assign(process.env, { DATABASE_URL: url.href, DATABASE_SSL: 'false', DEV_BYPASS_AUTH: 'false', NODE_ENV: 'development', FRONTEND_URL: 'http://localhost:5173' });
  const { default: app } = await import('../src/app.js');
  const { default: pool } = await import('../src/lib/db.js');
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  const base = `http://127.0.0.1:${server.address().port}/api/auth`;
  const networkFetch = globalThis.fetch;
  const id = randomInt(100_000_000, 1_000_000_000);
  const email = `${randomUUID()}@github-test.invalid`;
  let verified = true;
  let providerFails = false;
  let providerCalls = [];
  const users = [];
  const states = [];
  const token = randomBytes(32).toString('base64url');
  t.mock.method(globalThis, 'fetch', async (url, options) => {
    providerCalls.push({ url, options });
    if (providerFails) throw new Error('Provider unavailable');
    if (url === 'https://github.com/login/oauth/access_token') return Response.json({ access_token: token });
    if (url === 'https://api.github.com/user') return Response.json({ id, login: 'test-developer' });
    if (url === 'https://api.github.com/user/emails') return Response.json([{ email, verified, primary: true }]);
    throw new Error('Unexpected provider URL');
  });
  const call = (path, options = {}) => networkFetch(`${base}${path}`, { redirect: 'manual', ...options });
  const begin = async () => {
    const response = await call('/github', { method: 'POST', headers: { Origin: process.env.FRONTEND_URL } });
    assert.equal(response.status, 200);
    const { authorizationUrl } = await response.json();
    const auth = new URL(authorizationUrl);
    const state = auth.searchParams.get('state');
    states.push(state);
    const cookie = response.headers.get('set-cookie').split(';')[0];
    assert.match(response.headers.get('set-cookie'), /HttpOnly;.*SameSite=Lax/i);
    assert.equal(auth.origin, 'https://github.com');
    assert.equal(auth.searchParams.get('scope'), 'user:email');
    assert.equal(auth.searchParams.get('code_challenge_method'), 'S256');
    const { rows: [stored] } = await pool.query('SELECT verifier FROM github_login_requests WHERE state_hash = $1', [createHash('sha256').update(state).digest('hex')]);
    assert.equal(auth.searchParams.get('code_challenge'), createHash('sha256').update(stored.verifier).digest('base64url'));
    return { state, cookie, verifier: stored.verifier };
  };
  const finish = (start, code = 'provider-test-code', cookie = start.cookie) => call(`/github/callback?state=${start.state}&code=${code}`, { headers: { Cookie: cookie } });
  const failure = (response, code) => {
    assert.equal(response.status, 303);
    assert.equal(new URL(response.headers.get('location')).searchParams.get('github_error'), code);
    assert.ok(!response.headers.get('set-cookie').includes('pomogit_session='));
  };
  try {
    delete process.env.GITHUB_CLIENT_ID;
    delete process.env.GITHUB_CLIENT_SECRET;
    delete process.env.GITHUB_CALLBACK_URL;
    const unavailable = await call('/github', { method: 'POST' });
    assert.equal(unavailable.status, 503);
    assert.match((await unavailable.json()).error, /not configured/);
    process.env.GITHUB_CLIENT_ID = 'test-client';
    process.env.GITHUB_CLIENT_SECRET = randomBytes(32).toString('base64url');
    process.env.GITHUB_CALLBACK_URL = 'http://localhost:5173/api/auth/github/callback';
    assert.equal((await call('/github', { method: 'POST', headers: { Origin: 'https://untrusted.invalid' } })).status, 403);
    const start = await begin();
    failure(await finish(start, 'code', 'pomogit_github=wrong'), 'github_state_invalid');
    assert.equal(providerCalls.length, 0);
    const response = await finish(start);
    assert.equal(response.headers.get('location'), 'http://localhost:5173/#work');
    const session = response.headers.getSetCookie().find(cookie => cookie.startsWith('pomogit_session='));
    assert.match(session, /HttpOnly;.*SameSite=Lax/i);
    const me = await call('/me', { headers: { Cookie: session.split(';')[0] } });
    assert.equal(me.status, 200);
    const owner = (await me.json()).user;
    users.push(owner.id);
    assert.equal(owner.email, email);
    const exchange = new URLSearchParams(providerCalls[0].options.body);
    assert.equal(exchange.get('code_verifier'), start.verifier);
    assert.equal(exchange.get('redirect_uri'), process.env.GITHUB_CALLBACK_URL);
    assert.ok(!JSON.stringify(owner).includes(token));
    failure(await finish(start), 'github_state_invalid');
    const repeat = await finish(await begin());
    const repeatSession = repeat.headers.getSetCookie().find(cookie => cookie.startsWith('pomogit_session='));
    assert.equal((await (await call('/me', { headers: { Cookie: repeatSession.split(';')[0] } })).json()).user.id, owner.id);
    assert.equal((await call('/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password: 'guess' }) })).status, 401);
    const expired = await begin();
    await pool.query('UPDATE github_login_requests SET expires_at = NOW() - INTERVAL \'1 second\' WHERE state_hash = $1', [createHash('sha256').update(expired.state).digest('hex')]);
    failure(await finish(expired), 'github_state_invalid');
    const cancelled = await begin();
    failure(await call(`/github/callback?state=${cancelled.state}&error=access_denied`, { headers: { Cookie: cancelled.cookie } }), 'github_cancelled');
    await pool.query('UPDATE users SET banned = true WHERE id = $1', [owner.id]);
    failure(await finish(await begin()), 'github_suspended');
    await pool.query('DELETE FROM users WHERE id = $1', [owner.id]);
    verified = false;
    failure(await finish(await begin()), 'github_email_required');
    verified = true;
    const registered = await call('/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password: randomUUID() }) });
    const emailUser = (await registered.json()).user;
    users.push(emailUser.id);
    failure(await finish(await begin()), 'github_email_taken');
    assert.equal((await pool.query('SELECT github_id FROM users WHERE id = $1', [emailUser.id])).rows[0].github_id, null);
    providerFails = true;
    failure(await finish(await begin()), 'github_unavailable');
    providerCalls = [];
    failure(await call('/github/callback?state[]=bad&code[]=bad'), 'github_unavailable');
    assert.equal(providerCalls.length, 0);
    assert.equal((await pool.query('SELECT COUNT(*)::int AS count FROM auth_sessions WHERE user_id = $1', [emailUser.id])).rows[0].count, 1);
  } finally {
    await pool.query('DELETE FROM users WHERE id = ANY($1::text[])', [users]);
    await pool.query('DELETE FROM github_login_requests WHERE state_hash = ANY($1::text[])', [states.map(state => createHash('sha256').update(state).digest('hex'))]);
    await new Promise(resolve => server.close(resolve));
    await pool.end();
  }
});
